name: CI/CD Pipeline - Build, Push & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-push-deploy:
    runs-on: self-hosted 
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t mrhemanth/demo-app:latest -t mrhemanth/demo-app:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push mrhemanth/demo-app:latest
          docker push mrhemanth/demo-app:${{ github.sha }}

      - name: Deploy to local Minikube
        run: |
          sed -i '' "s|image:.*|image: mrhemanth/demo-app:${{ github.sha }}|g" k8s/deployment.yaml
          kubectl apply -f k8s/
          kubectl rollout status deployment/demo-app --timeout=120s
