name: CI/CD Pipeline - Build, Push & Deploy

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: mrhemanth/demo-app

jobs:
  # =======================
  # 1️⃣ Build Job
  # =======================
  build:
    runs-on: self-hosted
    outputs:
      sha: ${{ steps.vars.outputs.sha }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get short SHA
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ steps.vars.outputs.sha }} .
          echo "Built image: $IMAGE_NAME:${{ steps.vars.outputs.sha }}"

  # =======================
  # 2️⃣ Push Job
  # =======================
  push:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag & Push Image
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          docker tag $IMAGE_NAME:${SHORT_SHA} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${SHORT_SHA}
          echo "✅ Pushed $IMAGE_NAME:${SHORT_SHA} to Docker Hub"

  # =======================
  # 3️⃣ Deploy Job
  # =======================
  deploy:
    runs-on: self-hosted
    needs: push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Local Kubernetes (Minikube)
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "🚀 Deploying image $IMAGE_NAME:${SHORT_SHA} to local Minikube..."
          sed -i '' "s|image:.*|image: $IMAGE_NAME:${SHORT_SHA}|g" k8s/deployment.yaml
          kubectl apply -f k8s/
          kubectl rollout status deployment/demo-app --timeout=120s
